; PlatformIO Project Configuration File
;


[platformio]
default_envs = argb-511c
extra_configs = secrets.ini

[env]
; Global ESP32 Settings
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_compat_mode = strict
lib_ldf_mode = deep+
; Base build flags for all environments
build_flags = 
    -DESP32=1
    -DIGNORE_CRC_ERROR=true
    -DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
    -DCONFIG_LOG_COLORS=1
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_LOG_DEFAULT_LEVEL=3
    -DCONFIG_LOG_TIMESTAMP_SOURCE_NONE=1
    -Ilib/can-canbus-data/include
    -Ilib/can_personality/src
    -Ilib/can_producer/src
    -Ilib/can_router/src
; Base libraries for all environments
lib_deps = 
    can-canbus-data ; Canbus constants and such 
    can_router      ; CAN router library
    can_personality ; CAN Personality library
    can_producer    ; CAN Producer library



[env:cyd-86b0]
board = denky32
monitor_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
monitor_filters = esp32_exception_decoder 
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
; upload_protocol = espota
; upload_port = 192.168.2.127
; upload_flags = 
;    --auth="${secrets.OTA_PASSWORD}"
build_flags = 
    ${env.build_flags} 
    -DRX_PIN=27 ; blue wire
    -DTX_PIN=22 ; yellow wire
    -DESP32CYD
    -DNODE_TYPE=ESP_CYD
    -DNODEMSGID=0x792 ; LCD Touchscreen type A
    -DNODEMSGDLC=6
    -DUSER_SETUP_LOADED=1
    -DILI9341_2_DRIVER=1
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTOUCH_CS=33
    -DTFT_BACKLIGHT_ON=HIGH
    -DDETACH_WIFI=0
    -DSPI_FREQUENCY=55000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000
    -DLOAD_GLCD=1
    -DLOAD_FONT2=1
    -DLOAD_FONT4=1
    -DLOAD_FONT6=1
    -DLOAD_FONT7=1
    -DLOAD_FONT8=1
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1
    -DUSE_HSPI_PORT=1
lib_deps =
    ${env.lib_deps}
    espcyd
    bodmer/TFT_eSPI @ ^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git


[env:m5stamp-pico]
board = m5stamp-pico
monitor_port = /dev/serial/by-id/usb-1a86_USB_Single_Serial_5319008543-if00
upload_port = /dev/ttyACM0
build_flags = 
    ${env.build_flags} 
    -DESP32PICO
    -DARGB_LED
    -DNODE_TYPE=ARGB_MULTI
    -DRX_PIN=21
    -DTX_PIN=22
    -DARGB_DATA_PIN=27
    -DARGB_NUM_LEDS=1
    -DNODEMSGID=0x79C ; DISP_ARGB_LED_STRIP_ID
    -DNODEMSGDLC=7    ; DISP_ARGB_LED_STRIP_DLC
lib_deps =
    ${env.lib_deps}
    makuna/NeoPixelBus @ ^2.8.4
lib_ignore = 
    ${env.lib_ignore}
    espcyd

[env:pico-argb]
board = m5stamp-pico
monitor_port = /dev/ttyACM2
upload_port = /dev/ttyACM2
build_flags = 
    ${env.build_flags} 
    -DESP32PICO
    -DNODE_TYPE=ARGB_MULTI
    -DARGB_LED
    -DRX_PIN=21        ; Labeled SCK
    -DTX_PIN=22        ; Labeled MOSI
    -DARGB_DATA_PIN=27 ; Built-in LED
    -DARGB_NUM_LEDS=1
    -DNODEMSGID=0x79C ; DISP_ARGB_LED_STRIP_ID
    -DNODEMSGDLC=7    ; DISP_ARGB_LED_STRIP_DLC
lib_deps =
    ${env.lib_deps}
lib_ignore = 
    ${env.lib_ignore}
    espcyd


[env:argb-6d84]
board = m5stamp-pico
monitor_port = /dev/ttyACM2
monitor_filters = esp32_exception_decoder 
; upload_port = /dev/ttyACM2
upload_protocol = espota
upload_port = 192.168.2.200
upload_flags = 
   --auth="${secrets.OTA_PASSWORD}"
build_flags = 
    ${env.build_flags} 
    -DESP32PICO
    -DNODE_TYPE=ARGB_MULTI
    -DARGB_LED
    -DRX_PIN=21        ; Labeled SCK
    -DTX_PIN=22        ; Labeled MOSI
    -DARGB_DATA_PIN=27 ; Built-in LED
    -DARGB_NUM_LEDS=1
    -DNODEMSGID=0x79C ; DISP_ARGB_LED_STRIP_ID
    -DNODEMSGDLC=7    ; DISP_ARGB_LED_STRIP_DLC
lib_deps =
    ${env.lib_deps}
    makuna/NeoPixelBus @ ^2.8.4
lib_ignore = 
    ${env.lib_ignore}
    espcyd


[env:argb-571c]
board = m5stamp-pico
monitor_port = /dev/ttyACM2
monitor_filters = esp32_exception_decoder 
upload_protocol = espota
upload_port = 192.168.2.163
upload_flags = 
   --auth="${secrets.OTA_PASSWORD}"
build_flags = 
    ${env.build_flags} 
    -DNODE_TYPE=ARGB_MULTI
    -DESP32PICO
    -DARGB_LED
    -DRX_PIN=21        ; Labeled SCK
    -DTX_PIN=22        ; Labeled MOSI
    -DARGB_DATA_PIN=27 ; Built-in LED
    -DARGB_NUM_LEDS=1
    -DNODEMSGID=0x79C ; DISP_ARGB_LED_STRIP_ID
    -DNODEMSGDLC=7    ; DISP_ARGB_LED_STRIP_DLC
lib_deps =
    ${env.lib_deps}
    makuna/NeoPixelBus @ ^2.8.4
lib_ignore = 
    ${env.lib_ignore}
    espcyd


[env:argb-511c]
board = m5stamp-pico
monitor_port = /dev/ttyACM2
monitor_filters = esp32_exception_decoder 
; upload_port = /dev/ttyACM2
upload_protocol = espota
upload_port = 192.168.2.137
upload_flags = 
   --auth="${secrets.OTA_PASSWORD}"
build_flags = 
    ${env.build_flags} 
    -DESP32PICO
    -DNODE_TYPE=ARGB_511C
    -DARGB_LED
    -DRX_PIN=21        ; Labeled SCK
    -DTX_PIN=22        ; Labeled MOSI
    -DARGB_DATA_PIN=19 ; CS pin
    -DARGB_NUM_LEDS=12 ; ARGB Ring
    -DNODEMSGID=0x79C ; DISP_ARGB_LED_STRIP_ID
    -DNODEMSGDLC=7    ; DISP_ARGB_LED_STRIP_DLC
lib_deps =
    ${env.lib_deps}
    makuna/NeoPixelBus @ ^2.8.4
lib_ignore = 
    ${env.lib_ignore}
    espcyd


[env:m5stack-atoms3]
board = m5stack-atoms3
build_flags = 
    ${env.build_flags} 
    -DESP32ATOMS3
    -DNODE_TYPE=ARGB_MULTI
    -DARGB_LED
    -DRX_PIN=22
    -DTX_PIN=21
    -DNODEMSGID=0x79C ; DISP_ARGB_LED_STRIP_ID
    -DNODEMSGDLC=6    ; DISP_ARGB_LED_STRIP_DLC
lib_deps =
    ${env.lib_deps}
    makuna/NeoPixelBus @ ^2.8.4
lib_ignore = 
    ${env.lib_ignore}
    espcyd


[env:ws-7in-touch]
board = esp32-s3-devkitc1-n16r8
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
board_build.extra_flags = -DBOARD_HAS_PSRAM
build_flags = 
    ${env.build_flags} 
    -DRX_PIN=19
    -DTX_PIN=20
    -DESP32WS7
    -DNODEMSGID=0x792 ; LCD Touchscreen type A
    -DNODEMSGDLC=6
    -DSCREEN_WIDTH=800
    -DSCREEN_HEIGHT=480
lib_deps =
    ${env.lib_deps}
lib_ignore = 
    ${env.lib_ignore}
    espcyd

[env:waveshare_7inch]
board = esp32-s3-devkitc-1
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
build_flags = 
    ${env.build_flags}
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    ${env.lib_deps}
    tamctec/TAMC_GT911 @ ^1.0.2
    moononournation/Arduino_GFX @ ^1.6.5
lib_ignore = 
    ${env.lib_ignore}
    espcyd